---
- name: IOS ROUTER POST REBOOT VERSION CHECK
  hosts: all
  connection: network_cli
  gather_facts: no

  vars:
    ansible_network_os: ios
    compliant_ios_version: 15.7(3)M3

  tasks:
    - name: WAIT FOR ROUTER TO RESPOND
      local_action: wait_for
      args:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 15
        timeout: 600

    - name: GATHER IOS ROUTER FACTS
      ios_facts:
        gather_subset:
          - hardware

    - name: SET MODEL VARIABLE C1841
      set_fact:
        router_model: 'c1841'
        compliant_ios_version: 15.1(4)M12a
      when: '"c1841" in ansible_net_image'

    - name: SET MODEL VARIABLE C1900
      set_fact:
        router_model: 'c1900'
        compliant_ios_version: 15.8(3)M0a
      when: '"c1900" in ansible_net_image'

    - name: SET MODEL VARIABLE C2800
      set_fact:
        router_model: 'c2800'
        compliant_ios_version: 15.1(4)M12a
      when: '"c2800nm" in ansible_net_image'

    - name: SET MODEL VARIABLE C3900e SERIES
      set_fact:
        router_model: 'c3900e'
      when: '"c3900e" in ansible_net_image'

    - name: SET MODEL VARIABLE C899
      set_fact:
        router_model: 'c800'
        compliant_ios_version: 15.8(3)M2
      when: '"c800" in ansible_net_image'

    - name: SET MODEL VARIABLE IR829
      set_fact:
        router_model: 'ir800'
        compliant_ios_version: 15.8(3)M0a
      when: '"ir800" in ansible_net_image'

    - name: SET MODEL VARIABLE ISR4300
      set_fact:
        router_model: 'isr4300'
        compliant_ios_version: 16.06.05
      when: '"isr4300" in ansible_net_image'

    - name: SET MODEL VARIABLE ISR4400
      set_fact:
        router_model: 'isr4400'
        compliant_ios_version: 16.06.05
      when: '"isr4400" in ansible_net_image'

    - debug: msg="COMPLIANT IOS VERSION {{ compliant_ios_version }}\nRUNNING IOS VERSION {{ ansible_net_version }}"

    - name: SHOW STATUS ITEMS
      ios_command:
        commands:
          - "sh ip int brief"
          - "sh cdp neigh"
          - "sh ip bgp summ"
      register: sh_status

    - debug: msg='{{sh_status.stdout}}'

    - name: ASSERT THAT THE IOS VERSION IS CORRECT
      assert:
        that:
          - compliant_ios_version == ansible_net_version
